AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy an EC2 instance
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'                # Free-tier eligible instance type
      ImageId: 'ami-0c55b159cbfafe1f0'        # Amazon Linux 2 AMI ID
      KeyName: 'monitorssh'                # Replace with your SSH key pair name
      Tags:
        - Key: Name
          Value: MyFirstInstance
